# Generated by Django 3.0.6 on 2021-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
